export const userData = [
  {
    name: "Jan",
    "Active User": 4000,
  },
  {
    name: "Feb",
    "Active User": 3000,
  },
  {
    name: "Mar",
    "Active User": 5000,
  },
  {
    name: "Apr",
    "Active User": 4000,
  },
  {
    name: "May",
    "Active User": 3000,
  },
  {
    name: "Jun",
    "Active User": 2000,
  },
  {
    name: "Jul",
    "Active User": 4000,
  },
  {
    name: "Agu",
    "Active User": 3000,
  },
  {
    name: "Sep",
    "Active User": 4000,
  },
  {
    name: "Oct",
    "Active User": 1000,
  },
  {
    name: "Nov",
    "Active User": 4000,
  },
  {
    name: "Dec",
    "Active User": 3000,
  },
];

export const productData = [
  {
    name: "Jan",
    Sales: 4000,
  },
  {
    name: "Feb",
    Sales: 3000,
  },
  {
    name: "Mar",
    Sales: 5000,
  },
];

export const userRows = [
  {
    id: 1,
    username: "John Doe",
    avatar: "../../img/profileImg.webp",
    email: "johndoe@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 2,
    username: "Jane Doe",
    avatar: "../../img/profileImg.webp",
    email: "janedoe@gmail.com",
    status: "active",
    transaction: "$100.00",
  },
  {
    id: 3,
    username: "Jon Snow",
    avatar: "../../img/profileImg.webp",
    email: "jon@gmail.com",
    status: "disabled",
    transaction: "$0.00",
  },
  {
    id: 4,
    username: "Snow White",
    avatar: "../../img/profileImg.webp",
    email: "snow@gmail.com",
    status: "active",
    transaction: "$199.00",
  },
  {
    id: 5,
    username: "Jon Smith",
    avatar: "../../img/profileImg.webp",
    email: "jsmith@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 6,
    username: "Ahmed Aly",
    avatar: "../../img/profileImg.webp",
    email: "ahmed@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 7,
    username: "Reham Kassem",
    avatar: "../../img/profileImg.webp",
    email: "reham@gmail.com",
    status: "active",
    transaction: "$250.00",
  },
  {
    id: 8,
    username: "Habiba Aly",
    avatar: "../../img/profileImg.webp",
    email: "habiba@gmail.com",
    status: "active",
    transaction: "$10.00",
  },
  {
    id: 9,
    username: "Menna Aly",
    avatar: "../../img/profileImg.webp",
    email: "menna@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 10,
    username: "Sara Aly",
    avatar: "../../img/profileImg.webp",
    email: "sara@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 11,
    username: "John Doe",
    avatar: "../../img/profileImg.webp",
    email: "johndoe@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 12,
    username: "Jane Doe",
    avatar: "../../img/profileImg.webp",
    email: "janedoe@gmail.com",
    status: "active",
    transaction: "$100.00",
  },
  {
    id: 13,
    username: "Jon Snow",
    avatar: "../../img/profileImg.webp",
    email: "jon@gmail.com",
    status: "disabled",
    transaction: "$0.00",
  },
  {
    id: 14,
    username: "Snow White",
    avatar: "../../img/profileImg.webp",
    email: "snow@gmail.com",
    status: "active",
    transaction: "$199.00",
  },
  {
    id: 15,
    username: "Jon Smith",
    avatar: "../../img/profileImg.webp",
    email: "jsmith@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 2,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 3,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 4,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 5,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 6,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 7,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 8,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 9,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 10,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
];
